name: reviewdog
on:
  push:
  pull_request:
jobs:
  pycodestyle:
    name: pycodestyle
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: python styleguide
      uses: wemake-services/wemake-python-styleguide
    #- name: pycodestyle
    #  uses: ankitvgupta/pycodestyle-action@master
    #  env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #     PRECOMMAND_MESSAGE: You have style errors. See them below.
